// Code generated by "stringer -type=BuiltinType"; DO NOT EDIT.

package template

import "fmt"

const _BuiltinType_name = "SpanStoppingShuffleCycleIfStatementUnlessStatement"

var _BuiltinType_index = [...]uint8{0, 4, 12, 19, 24, 35, 50}

func (i BuiltinType) String() string {
	if i < 0 || i >= BuiltinType(len(_BuiltinType_index)-1) {
		return fmt.Sprintf("BuiltinType(%d)", i)
	}
	return _BuiltinType_name[_BuiltinType_index[i]:_BuiltinType_index[i+1]]
}
