// Code generated by "stringer -type=RelationType"; DO NOT EDIT.

package index

import "fmt"

const _RelationType_name = "ManyToManyOneToManyManyToOneOneToOne"

var _RelationType_index = [...]uint8{0, 10, 19, 28, 36}

func (i RelationType) String() string {
	if i < 0 || i >= RelationType(len(_RelationType_index)-1) {
		return fmt.Sprintf("RelationType(%d)", i)
	}
	return _RelationType_name[_RelationType_index[i]:_RelationType_index[i+1]]
}
