// Code generated by "stringer -type=ListeningState"; DO NOT EDIT.

package tests

import "fmt"

const _ListeningState_name = "ListeningLaughing"

var _ListeningState_index = [...]uint8{0, 9, 17}

func (i ListeningState) String() string {
	if i < 0 || i >= ListeningState(len(_ListeningState_index)-1) {
		return fmt.Sprintf("ListeningState(%d)", i)
	}
	return _ListeningState_name[_ListeningState_index[i]:_ListeningState_index[i+1]]
}
