// Code generated by "stringer -type=SecretState"; DO NOT EDIT.

package tests

import "fmt"

const _SecretState_name = "SecretNotSecret"

var _SecretState_index = [...]uint8{0, 6, 15}

func (i SecretState) String() string {
	if i < 0 || i >= SecretState(len(_SecretState_index)-1) {
		return fmt.Sprintf("SecretState(%d)", i)
	}
	return _SecretState_name[_SecretState_index[i]:_SecretState_index[i+1]]
}
