// Code generated by "stringer -type=SingularPlural"; DO NOT EDIT.

package tests

import "fmt"

const _SingularPlural_name = "SingularNamedPluralNamed"

var _SingularPlural_index = [...]uint8{0, 13, 24}

func (i SingularPlural) String() string {
	if i < 0 || i >= SingularPlural(len(_SingularPlural_index)-1) {
		return fmt.Sprintf("SingularPlural(%d)", i)
	}
	return _SingularPlural_name[_SingularPlural_index[i]:_SingularPlural_index[i+1]]
}
