// Code generated by "stringer -type=StandingState"; DO NOT EDIT.

package tests

import "fmt"

const _StandingState_name = "StandingSitting"

var _StandingState_index = [...]uint8{0, 8, 15}

func (i StandingState) String() string {
	if i < 0 || i >= StandingState(len(_StandingState_index)-1) {
		return fmt.Sprintf("StandingState(%d)", i)
	}
	return _StandingState_name[_StandingState_index[i]:_StandingState_index[i+1]]
}
