// Code generated by "stringer -type=TriState"; DO NOT EDIT.

package tests

import "fmt"

const _TriState_name = "NoYesMaybe"

var _TriState_index = [...]uint8{0, 2, 5, 10}

func (i TriState) String() string {
	if i < 0 || i >= TriState(len(_TriState_index)-1) {
		return fmt.Sprintf("TriState(%d)", i)
	}
	return _TriState_name[_TriState_index[i]:_TriState_index[i+1]]
}
