// Code generated by "stringer -type=EventPhase"; DO NOT EDIT.

package event

import "fmt"

const _EventPhase_name = "PhaseNoneCapturingPhaseAtTargetBubblingPhaseAfterPhase"

var _EventPhase_index = [...]uint8{0, 9, 23, 31, 44, 54}

func (i EventPhase) String() string {
	if i < 0 || i >= EventPhase(len(_EventPhase_index)-1) {
		return fmt.Sprintf("EventPhase(%d)", i)
	}
	return _EventPhase_name[_EventPhase_index[i]:_EventPhase_index[i+1]]
}
