// Code generated by "stringer -type=Options"; DO NOT EDIT.

package event

import "fmt"

const (
	_Options_name_0 = "DefaultCaptureTargetOnly"
	_Options_name_1 = "RunAfter"
)

var (
	_Options_index_0 = [...]uint8{0, 7, 14, 24}
	_Options_index_1 = [...]uint8{0, 8}
)

func (i Options) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Options_name_0[_Options_index_0[i]:_Options_index_0[i+1]]
	case i == 4:
		return _Options_name_1
	default:
		return fmt.Sprintf("Options(%d)", i)
	}
}
