// Code generated by "stringer -type=Type"; DO NOT EDIT.

package item

import "fmt"

const _Type_name = "ErrorEndExpressionFunctionReferenceKeywordLeftBracketFilterRightBracketSpaceText"

var _Type_index = [...]uint8{0, 5, 8, 18, 26, 35, 42, 53, 59, 71, 76, 80}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
