// headerTemplate.js
'use strict';
module.exports =
`// Code generated by "makeops"; edit at your own risk.
package {{package}}

import (
  "github.com/ionous/iffy/dl/composer"
  "github.com/ionous/iffy/rt"
)
`
