// Code generated by "stringer -type=FloatMode"; DO NOT EDIT.

package chart

import "fmt"

const _FloatMode_name = "PendingInt10Int16Float64"

var _FloatMode_index = [...]uint8{0, 7, 12, 17, 24}

func (i FloatMode) String() string {
	if i < 0 || i >= FloatMode(len(_FloatMode_index)-1) {
		return fmt.Sprintf("FloatMode(%d)", i)
	}
	return _FloatMode_name[_FloatMode_index[i]:_FloatMode_index[i+1]]
}
