// Code generated by "stringer -type=CommonProper"; DO NOT EDIT.

package std

import "fmt"

const _CommonProper_name = "CommonNamedProperNamed"

var _CommonProper_index = [...]uint8{0, 11, 22}

func (i CommonProper) String() string {
	if i < 0 || i >= CommonProper(len(_CommonProper_index)-1) {
		return fmt.Sprintf("CommonProper(%d)", i)
	}
	return _CommonProper_name[_CommonProper_index[i]:_CommonProper_index[i+1]]
}
