// Code generated by "stringer -type=ObjectGrouping"; DO NOT EDIT.

package test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WithoutObjects-0]
	_ = x[WithoutArticles-1]
	_ = x[WithArticles-2]
}

const _ObjectGrouping_name = "WithoutObjectsWithoutArticlesWithArticles"

var _ObjectGrouping_index = [...]uint8{0, 14, 29, 41}

func (i ObjectGrouping) String() string {
	if i < 0 || i >= ObjectGrouping(len(_ObjectGrouping_index)-1) {
		return "ObjectGrouping(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectGrouping_name[_ObjectGrouping_index[i]:_ObjectGrouping_index[i+1]]
}
