// Code generated by "stringer -type=PropertyType"; DO NOT EDIT

package rt

import "fmt"

const _PropertyType_name = "InvalidPropertyNumberTextPointerArrayNumberArrayTextArrayPointerArrayState"

var _PropertyType_index = [...]uint8{0, 15, 21, 25, 32, 37, 48, 57, 69, 74}

func (i PropertyType) String() string {
	if i < 0 || i >= PropertyType(len(_PropertyType_index)-1) {
		return fmt.Sprintf("PropertyType(%d)", i)
	}
	return _PropertyType_name[_PropertyType_index[i]:_PropertyType_index[i+1]]
}
