// Code generated by "stringer -type=CompareType"; DO NOT EDIT.

package core

import "fmt"

const (
	_CompareType_name_0 = "Compare_EqualToCompare_GreaterThan"
	_CompareType_name_1 = "Compare_LessThan"
)

var (
	_CompareType_index_0 = [...]uint8{0, 15, 34}
	_CompareType_index_1 = [...]uint8{0, 16}
)

func (i CompareType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CompareType_name_0[_CompareType_index_0[i]:_CompareType_index_0[i+1]]
	case i == 4:
		return _CompareType_name_1
	default:
		return fmt.Sprintf("CompareType(%d)", i)
	}
}
