// Code generated by "stringer -type=Flags"; DO NOT EDIT.

package pat

import "fmt"

const _Flags_name = "InfixPrefixPostfix"

var _Flags_index = [...]uint8{0, 5, 11, 18}

func (i Flags) String() string {
	if i < 0 || i >= Flags(len(_Flags_index)-1) {
		return fmt.Sprintf("Flags(%d)", i)
	}
	return _Flags_name[_Flags_index[i]:_Flags_index[i+1]]
}
