package pat

import (
	r "reflect"
)

// Rulebook associates patterns with the rules that give those patterns meaning.
// Rulebooks are generated by Contracts.
type Rulebook struct {
	Bools
	Numbers
	TextPatterns
	Objects
	NumLists
	TextLists
	ObjLists
	Executes
}

type Bools map[r.Type]BoolRules
type Numbers map[r.Type]NumberRules
type TextPatterns map[r.Type]TextRules
type Objects map[r.Type]ObjectRules
type NumLists map[r.Type]NumListRules
type TextLists map[r.Type]TextListRules
type ObjLists map[r.Type]ObjListRules
type Executes map[r.Type]ExecuteRules

func MakeRulebook() Rulebook {
	return Rulebook{
		make(Bools),
		make(Numbers),
		make(TextPatterns),
		make(Objects),
		make(NumLists),
		make(TextLists),
		make(ObjLists),
		make(Executes),
	}
}
